# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a54e9be5f7179aeb203b5eb0c6697ce2fa9d1b1a40e1cbe8e5ad5afc4017ee777de591257eb5708bd7d362621b51e7cf51d88dbf3139972e2bc57005bcdf8371

test:
  secret_key_base: 5c20baa68b537d752f5211dd7a195fa8208e2fc3aa05ff8ac3129374c610b1edf2749b4c037ca1f15d20a228696dd3acde9910b484ac9c8f3086b9c5ad8b164e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
